SKILL_KEYWORDS = {
    "python",
    "java",
    "c++",
    "sql",
    "mysql",
    "sqlite",
    "postgresql",
    "mongodb",
    "pandas",
    "numpy",
    "scikit-learn",
    "sklearn",
    "tensorflow",
    "keras",
    "pytorch",
    "machine learning",
    "deep learning",
    "nlp",
    "natural language processing",
    "computer vision",
    "data analysis",
    "data visualization",
    "dashboard",
    "dashboard development",
    "matplotlib",
    "seaborn",
    "plotly",
    "power bi",
    "tableau",
    "excel",
    "statistics",
    "probability",
    "eda",
    "exploratory data analysis",
    "linear regression",
    "logistic regression",
    "random forest",
    "xgboost",
    "tf-idf",
    "cosine similarity",
    "classification",
    "clustering",
    "feature engineering",
    "model evaluation",
    "streamlit",
    "html",
    "css",
    "javascript",
    "git",
    "github",
    "docker",
    "linux",
    "api",
    "rest api",
    "database design",
    "data modeling",
    "pdf processing",
    "report generation",
    "software engineering",
    "data structures",
    "algorithms",
    "oop",
    "agile",
    "etl",
    "data cleaning",
    "data preprocessing",
    "text preprocessing",
    "web scraping",
    "beautifulsoup",
    "selenium",
}


RECOMMENDATION_MAP = {
    "python": ["pandas", "numpy", "scikit-learn", "streamlit"],
    "machine learning": ["feature engineering", "model evaluation", "statistics"],
    "data analysis": ["sql", "excel", "power bi", "tableau"],
    "nlp": ["spaCy", "NLTK", "TF-IDF", "text preprocessing"],
    "streamlit": ["plotly", "sqlite", "pdf processing"],
    "sql": ["sqlite", "postgresql", "data modeling"],
    "tf-idf": ["cosine similarity", "text preprocessing", "model evaluation"],
    "data visualization": ["plotly", "matplotlib", "dashboard development"],
}
